apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:nrTDXKiRqNB9VXeoGmTSathIFJtLaYvQCO1qlij2KDxCfTmEwhUJuw==,iv:MPCNbdUWU7usIivp1TQnYoM9L9huKWUp7y9aXTVWfH0=,tag:41+K66C22+IHi2KRiRbB9g==,type:str]
sops:
  age:
    - recipient: age1g4urhvnh3u4trxntghflfd0rme9734mnm905xfl4x24j20jrne3s4f4g7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWm1Bd0Uwb2dLcUU3MzRF
        TnM5aDZ0blFGT3JuUnl1S3lNcFVXekwxYUFZClEyRDcyb3FlQWZRUDdzNFNFeEdL
        c0hNSjM5aEE3OThJMlF1bDUvQWpkMzQKLS0tIGx1Ris0N25VSmxSd3RnRHVOT3g2
        VWgwYlNPR1FPbzBMNXhUdFdxZ20rb0UKyq1D5BtTWb41Nj4JPUqm8XrM8U8dtGBh
        uxIb6yZEsy6bM0XyoX9D/08Kq7g5rnFg8gaAzrML/juUxwdvUE9vdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-30T00:28:19Z"
  mac: ENC[AES256_GCM,data:lNbnnb384k50fWIzghDKrFSn6fHrIu90HNf1tiKdshrunbsEeT4ihgdZ0w0/AhkcqKO1H8cBxyh4jMqD9PQwopFMouLpoYogmsB8Ka+X0lJGDSc+HoqWkrKS7PmDSfRHsQPqctvmzSrNd/RSPMQpEfx7RulCW7UQReXOTNLncEw=,iv:Y99QmlYnwEM1kLh1USX57gHebINd6I2SlNDPOhHYesI=,tag:BTf1VwsVnbjkjCK2Wx+yAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
