apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:N4n55LXAYxZ0WmGIPWmr2cOL6TP5jiJEKgnsUIKgulnVGeAU/xRKRA==,iv:xfvuiW1hgxHmgE70Y/C7EJviKjDx99EZ/YQoJf2cDqg=,tag:K2as4b8jcxHz2eo29OLgQg==,type:str]
sops:
  age:
    - recipient: age1g4urhvnh3u4trxntghflfd0rme9734mnm905xfl4x24j20jrne3s4f4g7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK0JrQWhvNExYSlZoZTg1
        OTFkVjdIQk82UytlUGNlV21SbFM3d3RRSjBjCnMyS2Rha0pyVW1YM2NTU3lOZ2RC
        dU1PSExHZGhHM01RdGRoM0IwMnpBTjAKLS0tIDYzTmdPSXNreGpleTFyVWxFL0ZY
        TStqK296ZmxTb0NaWUdZTXFBT1NwQncKGa++ukc7p2/7NQMC79ct5oaZGaFvr32L
        +Hv0Sn9KBzVDSAuQMwqbKRI7XUBqYDMv7S32abzSYS3r4+rtYJbHmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-27T19:44:40Z"
  mac: ENC[AES256_GCM,data:EvmZxaRy4izEdfUrEp5MYuF/wEFs5puOHEYPRtZO0dWMlXMGO51gn1vI7X9XmhyUMmu0pZ9frH/6FL0uZXmeAcVduusmsENLfIdqgy4U6P6NeMaGG1yUB1GYUuFGWUAU/6HFSgsVbEWu9wCH6Q6kQD4Ti9SY5zIjVhJf2VFQ/pc=,iv:j84cSn7fP4yul97hHQZpbmPsV0AdFP7U423/zep3JH8=,tag:YCynWbBNBzzSfO2t5JIclw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
