apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:eP2WZf7NUk/XH5xW,iv:2AbipP+PaeqgPux7ZfQhg8dzT2tUnAtYI2DBiCkipHs=,tag:fdgdm7zIK+5545vtSI9RXg==,type:str]
sops:
  age:
    - recipient: age1g4urhvnh3u4trxntghflfd0rme9734mnm905xfl4x24j20jrne3s4f4g7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRXlZQmlIcU5xblI0eGhj
        eGViTE1KdVAveEE4UEJRV0dtV0tVVm5VVG1vCksvT0hZOTZMeDhvQ2NyamhYN2pS
        Mk5qbzBBbTJSVXloZU44bk1jUnArbGcKLS0tIHJjTFBPWEo1WFYyWEQ0VDh5bWhz
        QTBiNlJtTkhWUUZIbW1aS09ndFVBSUUKxFOX0+lkcVbS+9Kn2HbF+4rHPV7KLMvP
        ErH/mj90pJHBUk1oaGoqHmkLlIzxUS28qfQtRd0Kjcxv+tON+qmSQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-30T00:28:20Z"
  mac: ENC[AES256_GCM,data:UoEMFJxBoJdyfgVDbzqrcoRa4nHfOcUaWPcXCAd5dKtpBc8072VldOOgD3jV48jW4w/L99y+nKCYyTUA8KzghJh3WNkv+76ZKv8TSDJruwxQvRe0yTLx+V4VyBu94cXFG3q6Ix47S6CfqcFcfhe2v9HAIYhlkDxgEj8gaIEwY7g=,iv:CU5eJ7Xf4bncYfmtqrRXO2Cd1hjsSSHqTx+nTH+p1x8=,tag:J4DOo6INyopUa2V4nDIy6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
