apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:OJ0E8k0tKPvWXZiZdcV2KDSNW7zq0cRLyNh16LVnmPU=,iv:oCYhDhd4RKahPPwtgZlf/znE8XSloLOXFHhC12F++Oc=,tag:ZyIDjhh/LwtkER/p8LW5TQ==,type:str]
sops:
  age:
    - recipient: age1g4urhvnh3u4trxntghflfd0rme9734mnm905xfl4x24j20jrne3s4f4g7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSnJnRmdHcUlWNE1pRFBm
        K3JHRWdQVU43MnBvZnpISVJ0YlgvaURROXo4Ci9lUi9tUmpBSTlZUXVMRWpUb3U3
        MWxSbndtTXlGWFpoNi9mUjZkTDVGY0EKLS0tIDJqNmh2MXdJWGFsQ1Rjc1BNY1Zh
        MC9HcmVET2tQOVRjUWtZQ25NTkhabVUKBgMTVnfEhYD7fsBdIIsmWzSZSm7SzesN
        zdnlykyHlQB3GzusP0MBycCORkQMhlCfttZlwQQlchvga4mr1LTCfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-30T00:28:19Z"
  mac: ENC[AES256_GCM,data:nGQleyEbyYAjKMmutNBuWNiaKZcahkJZo6cYx496M2GTlUTBcEkjlo04A8ffYisEXFgtCJOgdySKIXm2FgpBV7wxBZzUnKVleKJrfAYx7qv5Rqk+0m1YQuY0xlSjgPTfwGytq7JeabhuA1FO8If6HRZymR7pg7KiOSY0/CGtuK8=,iv:HOssAbj4yyz5crA6i4to9BPdvLX0m+3+xvUeB7W4H08=,tag:I2F1E4Z1pRtWUo0qiQvpSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
