apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Sx3XVoCvdzO4YmUItMbhwAdbmkQ1EDJnnmhNv12dobGd0lWY1QlD3zqDPW4erVx494NuCMv2ERiJ1KkBsOV5mYozY1rMHFaGUVEI10sZlePgEqJJZldFa7iV9AdgqPO4K2t8QYzBh0yqZ+L3U/9mQp74TLP53lM4ccR+YqfI20arm1lL/1mRww59kCpiCnVm9Ih1GIQ/WPwi9q/8XzFnIV22mHJLAFDjhQA9+vzQp+R5rcXU,iv:W7OzvoUxzeA7qrCEKZUap8rE0MdoZH5Ov0spHRCMsXM=,tag:R0VKp6SbRnzopo6N/Hn9eQ==,type:str]
sops:
  age:
    - recipient: age1g4urhvnh3u4trxntghflfd0rme9734mnm905xfl4x24j20jrne3s4f4g7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bFRLUmlvaTBSZHZ1MDJP
        TmY3N1RhbmtqVWpVQlIyWEk2dkpkNzdCbEdJCmNMbGVJbE8wL2p5ODNyT0RSOFpP
        bXVnWU4yQlNBMTFMQ0xEZ1JXUWkzQ1EKLS0tIHZQRHBnVTRXeTJJTGtWODY4TmNt
        dHhXekVOcHlpQlQxUmJlRUkyMndWOE0KyF/e0aklSoToeTXvs4gUB3TFyOtS2f3g
        qm+T7F7Bgmz8wApD73RMqCte22s2OToGF33ddoRh4paZ7zCAd9td5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-27T19:44:40Z"
  mac: ENC[AES256_GCM,data:MNiaThATGh8AE29IdKxldWx33gF0JcMY1TLFPbGst4CylPE99wrqEjE0NTF3v3icOjghaJlv2MepyoKe2p73yJ7VdI73VFIrDajT3lrOOcBaa+V+MfHPym5LPAIf5fDFS8nLEhydm5UFfaN9QaVum4ymSAnVsynociX/U/zFuuI=,iv:QcX9THtVmgT6v6B7zEQ1Qe0B3wJePQxXkNAkVtAwKEE=,tag:1DUDBI/c1xsMtfh64OQvAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
