apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:kNPijRdn1SNMC7zj76LNwNgqgxBrsFhSST8+Os/4zNeA5Aa5CT7rPrv1mENPc/6l6Aodp21RokzthosghQg1Nm2CmLXCXT9brX6ULpm0/TbXfoxfoNTfxY9YzmVdNMZ55mXybEBXbnXxQaxWdVBMXsTzzuuOdG8CllSUFsJgRMyBbGyn3x9XZt/PhF3jUvrPt9ZQN+OV0lS/CDowpCbp4COBkvzM2bUWCsCziu0JvtbnPvRR,iv:3FrQqgRLCUUjKPh+Ec405HA8f6iflHQk45iamlbouKM=,tag:aJLC3KWmfGghrN/3Y/DFHw==,type:str]
sops:
  age:
    - recipient: age1g4urhvnh3u4trxntghflfd0rme9734mnm905xfl4x24j20jrne3s4f4g7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc2FwMFFOVXhSUUp6RXQ2
        TUhuQnBDSWkxU0NpS1ZrNWl6Q014TDZDTVFRCmlidlVpUnkrUnRaMTNNNzRQUCtZ
        R1lBQUZhdjkyUm51VlJFZTc2clRkb3MKLS0tIG1BTStVQzJhcy9XNmxBQjBBeVFw
        S05XZzA5N2RLeFBHdEUxZm11a3lIS28K9QdwS9DCENmBdfyb4cyIY3+nXsnjCTFw
        WPcUBkWy82li8OsqMtbRMo0dsQSZemefPdnH7su0ScoZ6i1FKSadvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-30T00:28:20Z"
  mac: ENC[AES256_GCM,data:BO6GJf1lBgGKf6wLj/9ULlHC5ayoVeyuLl0NqLjwFWv37qL2U+7YsDrJcfc7WsePkYHPUDLzRC6WyBzWVgB68Ly7f0Wvu4NA5zvUG6thDHozaZ5IqRpc55urLI3UkguvX7atKueM0SlE/2YyHWfFy9/vlxsZKCpw/iCXTA9IJjE=,iv:telj1FYi0vob5veOW8nYWiX+Bque3lVpbj0lTWOn1I8=,tag:8Dm7ncFGxE1IBrDvfMbqdA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
