apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:KsDWabSul6+Jc2OONaRkB3llIDVJCNBRNJiqvt83hGQcoRTIOMVwNA==,iv:8q8iHCqQ3TwFBRBKAGpqBIc+h9MuYjAZDISJVb+XWUc=,tag:aZB1kvh1Xt85nYGWl3mENw==,type:str]
sops:
  age:
    - recipient: age1g4urhvnh3u4trxntghflfd0rme9734mnm905xfl4x24j20jrne3s4f4g7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3LzVJZTJNMlprUHE1Ujly
        QXd0bjNmazRHQUVDV21ZdkVubTNqVThnMndVCk5RT0pwYThzM0xBQU8rSUJteEpz
        d0F4L3RqbThDcDhtN3ViSGpCVG5PSmsKLS0tIHVsZlFFc3N0QURFVmV0aTRIUjd6
        S3FpT2MrbUpsLzlwdG1sUzhuTzQ2OUUKfcJ+RjuLtXC1ZYn/T8shdL3QBBRaUPen
        bC6oBLfmF+NjHETBwcncsJFMo0kWYULq/joFmtfSdCbAe1izfPwLgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-27T19:44:40Z"
  mac: ENC[AES256_GCM,data:aY8isx/nu2nVz2EBL1rjD5+N19gUHCIA7tm83ZxzQxMgqHaesh3KID6ihvJ9a/MMChzN8hB+I0Ig6vp7cYRZZBF7IiDE3VikzByKrBZz7Sr9xfd89St3Bcl+zXvvxZfjpW3fso1N9tIsP/1cHMvBTrGvManKzMnp4uSYlAkuyA0=,iv:MnEufQ2BxrGtdVX/AcMV7LWIgT+hyF55JeZJEIjQT+I=,tag:CEJrENQPn0Tt21EImpqJEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
