apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:uif7Nlg/cEyIgDRCXiyS2GW71xr0xE2UZpy++JWCHit1lz/bLNOf2A==,iv:s30QPxAFEJ+l7UF+M3VoO3oVrEMXEdlCoX0ozb336Oc=,tag:YWQJAp4miSCg+P5sanqGig==,type:str]
sops:
  age:
    - recipient: age1g4urhvnh3u4trxntghflfd0rme9734mnm905xfl4x24j20jrne3s4f4g7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxU1RCUHNBbXFFaFkrNm9D
        VS92VWFlRUxPdENNeFlDMUdaTnlQQVVWTWd3CjNjMmlWdE14bUppL1V4QzZSVEJv
        N2pGTERWN0twWkVJV2VwSEtseldZT1kKLS0tIFNDa283bG9iZzh5UTdsa3ZnRTFl
        bmYyOHZYN3pITVBnWkJnL2pTNzczWXcKHo/d0HRtga9oJfv5BYTeX3sjHe7cIFsL
        tf/Xpxdkdt9bBnhXadlnV+t8Jow5w0gha64cmC+rISG+OqBUnuZ7DQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-30T00:28:19Z"
  mac: ENC[AES256_GCM,data:cwWLczUOhIZLO8uK9Vs0zpkVOA8nrsreHVJWFFIZCyW6njzDfw7OgvCfp7kpkpBFs1Vk0XkXmyYrza63oYMCcIDOJsd088y5laZgMi6/CH3GBjGfW9+vDn7uPfIFHO7jPGfC9NtEE6abgf3l31jVL0WUGahHsh5Vipf1qVtlPFE=,iv:UWj7UVUSjmXKr/Rscun9OQ5LAniRvZmKieb+AvBWXLo=,tag:8KQk8lmQe34+AXVR+VBoDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
